apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hushkey-kv
  namespace: hushkey-ns
spec:
  provider: azure
  parameters:
    clientID: "__UAMI_CLIENTID__"
    keyvaultName: hushkey-kv
    tenantId: __TENANTID__
    objects: |
      array:
        - |
          objectName: "POSTGRES-USER"
          objectType: "secret"
        - |
          objectName: "POSTGRES-PASSWORD"
          objectType: "secret"
        - |
          objectName: "POSTGRES-HOST"
          objectType: "secret"
        - |
          objectName: "POSTGRES-PORT"
          objectType: "secret"
        - |
          objectName: "POSTGRES-DB"
          objectType: "secret"
  secretObjects:
    - secretName: db-secret
      type: Opaque
      data:
        - objectName: "POSTGRES-USER"
          key: POSTGRES_USER
        - objectName: "POSTGRES-PASSWORD"
          key: POSTGRES_PASSWORD
        - objectName: "POSTGRES-HOST"
          key: POSTGRES_HOST
        - objectName: "POSTGRES-PORT"
          key: POSTGRES_PORT
        - objectName: "POSTGRES-DB"
          key: POSTGRES_DB
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hushkey-api
  namespace: hushkey-ns
  labels:
    app: hushkey-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hushkey-api
  template:
    metadata:
      labels:
        app: hushkey-api
    spec:
      serviceAccountName: hushkeykv-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "hushkey-kv"
      containers:
        - name: hushkey-api
          image: ghcr.io/shikhar03stark/hushkeyapi:__IMAGE_TAG__
          ports:
            - containerPort: 5000
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES-HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES-PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES-DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES-USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES-PASSWORD
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: hushkey-api
  namespace: hushkey-ns
spec:
  type: ClusterIP
  selector:
    app: hushkey-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hushkey-api
  namespace: hushkey-ns
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: "hushkey-public-ip"
spec:
  rules:
    - host: hushkey.devitvish.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: hushkey-api
                port:
                  number: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hushkeykv-sa
  namespace: hushkey-ns
  annotations:
    azure.workload.identity/client-id: "__UAMI_CLIENTID__"
