name: Backend CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./backend/HushKey.sln
      - name: Build
        run: dotnet build --no-restore --configuration Release ./backend/HushKey.sln
      - name: Test
        run: dotnet test --no-build --configuration Release ./backend/HushKey.sln
      - name: Pack
        run: |
          mkdir -p artifacts/backend
          dotnet publish ./backend/src/HushKeyApi/HushKeyApi.csproj -c Release -o artifacts/backend/api
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-api
          path: artifacts/backend/api
