# This workflow builds and publishes the backend Docker image after backend.yml passes
name: Backend Docker Build & Publish

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  build-and-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next Docker image version
        id: next_version
        run: |
          chmod +x ./scripts/next-docker-version.sh
          VERSION=$(./scripts/next-docker-version.sh ${{ github.actor }} hushkeyapi)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Creating tag with semver $VERSION"

      - name: Set lowercase GitHub actor
        id: actor_lower
        run: echo "actor_lower=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ steps.actor_lower.outputs.actor_lower }}/hushkeyapi:${{ steps.next_version.outputs.version }}
