name: Deploy to AKS (Production)

on:
  workflow_run:
    workflows: ["Backend Docker Build & Publish"]
    types:
      - completed

jobs:
  deploy:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'master'
    name: Deploy to AKS
    runs-on: ubuntu-latest
    environment: prod
    env:
      AZURE_TENANT_ID: ${{ secrets.AZ_TENANTID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZ_SP_CLIENTSECRET }}
      AKS_RESOURCE_GROUP: ${{ secrets.AZ_RG }}
      AKS_CLUSTER_NAME: ${{ secrets.AZ_AKS_CLUSTERNAME }}
      AZURE_UAMI_CLIENT_ID: ${{ secrets.AZ_UAMI_CLIENTID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CLIENT_SECRET }}

      - name: Get AKS credentials
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Set execute permission for deploy.sh
        run: chmod +x ./scripts/*

      - name: Deploy to AKS
        run: ./scripts/deploy.sh ${{ env.AZURE_TENANT_ID }} ${{ env.AZURE_UAMI_CLIENT_ID }}
